#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 9 15
echo "$BASHPID" > /run/$(basename $0).pid
service squid3 stop
rm -rfv /var/spool/squid3/*
squid3 -z
service squid3 restart
echo -e "\e[00;1;92mFinished...\e[00m"
rm -f /run/$(basename $0).pid
exit 0
